version: "1.1"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password


  web:
    build: .
    ports:
      - 8080:8080
    environment:
      MANGODB_URI: "mangodb://root:password@mongo:27017/"
